### ISSUE TITLE
[SOLUTION] Internet Explorer (IE) support for older browsers (e.g. IE8 and IE7)

### ISSUE THREAD

**Issue by yanike** [nehakadam/DateTimePicker#108]
For IE8 and IE7 support (tested), you need to add the codes below.

This script needs to be added in the **DateTimePicker.js**  file before everything. This makes Object.keys work in legacy browsers.

```
/* Support Object.keys in IE8 */
if (!Object.keys) {
    Object.keys = function(obj) {
        var keys = [];

        for (var i in obj) {
            if (obj.hasOwnProperty(i)) {
                keys.push(i);
            }
        }

        return keys;
    };
}
```

This is very important as well. In old browsers, the DateTime Picker won't display if the input field is readonly. 

```
<!--[if lt IE 9 ]>
<script type="text/javascript">
  jQuery("#ELEMENTID).attr('readonly', false);
</script>
<![endif]-->
```

**Comment by gituid0** [comment]
In the above code, ELEMENTID should have a closing double quote, so it should read:
jQuery("#ELEMENTID").attr('readonly', false);
