### ISSUE TITLE
Picker breaks when opening/closing very fast.

### ISSUE THREAD

**Issue by jaskol** [nehakadam/DateTimePicker#11]
When I open/close picker very fast suddenly there is only an empty rectangle under the input instead of picker window. 

To fix this I tried to minimize "animationDuration" from 400 to 50.

**Comment by nehakadam** [comment]
Hi Jaskol

Yes, minimizing the "animationDuration" is a way to avoid closing of DateTimePicker since it is happening only when opening and closing happens very fast.

Thanks for reporting.
