### ISSUE TITLE
Setting a custom format for datetime

### ISSUE THREAD

**Issue by dreamxcape** [nehakadam/DateTimePicker#110]
Hi,

How can I set the input box selection format to this format: Jul 30, 2016 6:30 PM?
when i set data-format to "MMM dd, yyyy hh:mm AA" it doesn't work

**Comment by nehakadam** [comment]
Sorry, this DateTimeFormat is not supported. Supported DateTimeFormats are listed in [Documentation](https://curioussolutions.github.io/DateTimePicker/) as a Parameter Option `dateTimeFormat`.

**Comment by dreamxcape** [comment]
Ok, thanks for that :)
