### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by passion4IT** [nehakadam/DateTimePicker#118]
There is bug in the implementation. while getting the value from datetimepicker, following error is generated in console.
Uncaught RangeError: Maximum call stack size exceeded with jquery 3.1.0

**Comment by nehakadam** [comment]
I tested DateTimePicker Example with jquery 3.1.0 but did not get this error. Please check whether you get this error in any of the Demo included in demo folder of the repository.

**Comment by passion4IT** [comment]
Did u try typing some value on input field, rather than clicking + or -?. It generates some error and also print message in console

**Comment by nehakadam** [comment]
You may be facing this issue because of console messages printed on key press event. In case of simple example, I was not able to reproduce issue even after inputting value in the fields. Sorry, I forgot to comment it. Please comment line 1551 and try.

**Comment by passion4IT** [comment]
since i am using this plugin through npm module, it wont be an efficient way especially working in production environment.

**Comment by nehakadam** [comment]
Try minified file in dist folder with latest version 0.1.33. Could not publish to npm due to some error.
