### ISSUE TITLE
dynamically adding new date pickers

### ISSUE THREAD

**Issue by naveedhameed** [nehakadam/DateTimePicker#12]
Hi

We encountered an issue with the Date Time Picker when we dynamically allowed users to add and remove fields on our application forms.

The fix we found was the following function, it might come in handy for you guys

$.fn.ResetDateTimePicker = function (options) {
            return this.each(function () {
                if ($.data(this, "plugin_" + pluginName))
                    jQuery.removeData(this, "plugin_" + pluginName);

```
            if (!$.data(this, "plugin_" + pluginName)) {
                $.data(this, "plugin_" + pluginName, new DateTimePicker(this, options));
            }
        });
    };
```

What this allowed us to do was give the user the flexibility of adding and also removing date time picker fields, without compromising on functionality.

**Comment by nehakadam** [comment]
Hello,

Thanks for sharing your solution. We will incorporate a solution for this issue in the plugin.

This is another way to fix the issue - 

```
$.fn.DateTimePicker = function (options)
{
     return this.each(function() 
     {
          $.removeData(this, "plugin_" + pluginName);
          if(!$.data(this, "plugin_" + pluginName)) 
              $.data(this, "plugin_" + pluginName, new DateTimePicker(this, options));
     });
};
```

Let us know whether this alternative works for you.

Thank You.
