### ISSUE TITLE
format date or datetime on input text and on popup when choose date or datetime

### ISSUE THREAD

**Issue by ibnubay** [nehakadam/DateTimePicker#125]
For example:
On input text displayed date format is : yyyy-mm-dd
But when i click input text: the Popup to choose the date is: dd mm yyyy

![input_date](https://cloud.githubusercontent.com/assets/21232045/19845708/ff98614a-9f6b-11e6-8998-94c6cac7317c.png)

![set_tanggal](https://cloud.githubusercontent.com/assets/21232045/19845711/07eb3caa-9f6c-11e6-88b9-76f4223720ee.png)

Or it's already have example for that case?

Note: i already apply function "formatHumanDate" for header Format but the "Choose" format is not yet

Thanks before...

**Comment by nehakadam** [comment]
There is a similar example available - [BasicExamples-CustomInputValue.htm](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-CustomInputValue.htm)

Exact Solution for this Problem -

HTML Code -

```
<p>Date : </p>
<input id="input-date" type="text" data-field="date" data-format="dd-MM-yyyy" value="2016-07-05" readonly>

<div id="dateBox"></div>
```

Javascript Code - 

```
$(document).ready(function()
{
    var oDTP1;

    $("#dateBox").DateTimePicker(
    {
        parseDateTimeString: function(sDateTime, sMode, oInputElement)
        {
            oDTP1 = this;

            console.log(sDateTime + " " + sMode);
            var dThisDate = new Date(),
            iArrDateTimeComps, sRegex;

            if($.cf._isValid(sDateTime))
            {
                // "2016-10-26"
                sRegex = /(\d{1,4})(-)(\d{1,2})(-)(\d{1,2})/;

                iArrDateTimeComps = sDateTime.match(sRegex);


                dThisDate = new Date(
                    parseInt(iArrDateTimeComps[1]),
                    parseInt(iArrDateTimeComps[3]) - 1,
                    parseInt(iArrDateTimeComps[5]),
                    0, 0, 0, 0
                );
            }

            return dThisDate;
        },

        formatDateTimeString: function(oDate, sMode, oInputElement)
        {
            oDTP1 = this;

            console.log("formatDateTimeString");
            console.log(oDate);
            return oDate.yyyy + "-" + oDate.MM + "-" + oDate.dd;
        }
    });
});
```

**Comment by ibnubay** [comment]
can ask one more?
how to extend the code with add minDate or maxDate?
i already put "addEventHandlers" like this, but the date is chaos...

<img width="714" alt="screen shot 2016-11-01 at 12 53 25 am" src="https://cloud.githubusercontent.com/assets/21232045/19865161/b1fc86a2-9fcd-11e6-94e7-405f2d6b8530.png">

Like this
![sealtrax tms manage drivers](https://cloud.githubusercontent.com/assets/21232045/19865242/f19b44ec-9fcd-11e6-87e0-4ef5378e5844.png)

**Comment by nehakadam** [comment]
Please download latest version and try [this example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-CustomInputValue-Issue125.htm).
