### ISSUE TITLE
use it with asps page and runat="server"

### ISSUE THREAD

**Issue by juzamdjinn** [nehakadam/DateTimePicker#13]
Hi, if i try to use it with runat="server" in aspx page , input become invisible it exist on page but it was decorated with attributes that hide the control ( i call the page from desktop with IE 11)

it is rendered in this way 

<input name="ctl00$cphBody$MessageCreator$datetimepickerInizio" 
class="dtpicker-overlay dtpicker-mobile" id="ctl00_cphBody_MessageCreator_datetimepickerInizio" type="text" data-field="date">
<div class="dtpicker-bg">
<div class="dtpicker-cont">
<div class="dtpicker-content">
<div class="dtpicker-subcontent"></div></div></div></div></input>

thank you

**Comment by nehakadam** [comment]
Hello,

We have tested the plugin on IE 11. It is working fine.

From the snippet you included, it seems like you have initialized the plugin on the input element. But you are supposed to initialize it on the block level element you added specifically for DateTimePicker.

Please make sure that you have followed the steps listed while implementing -
1. Include CSS and JS files
   
   ```
    <link rel="stylesheet" type="text/css" href="DateTimePicker.css" />
    <script type="text/javascript" src="DateTimePicker.js"></script>
   ```
2. In .html(or .aspx), add input element
   
   ```
    <input type="text" data-field="date" readonly>
   ```
3. In .html(or .aspx), add element as a base element for DateTimePicker
   
   ```
    <div id="dtBox"></div>
   ```
4. In script, initialize the plugin,
   
   ```
    $(document).ready(function()
    {
         $("#dtBox").DateTimePicker();
    });
   ```

Please refer to [DateTimePicker Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicDatePicker.htm)

Also check [Demo](http://curioussolutions.github.io/DateTimePicker/) on IE 11.

Thank You.

**Comment by juzamdjinn** [comment]
Hi, thank you for answer,
if i use a simple input element alla works fine , but if i decorated it
with runat="server"
something change.
(es: <input type="text" data-field="date" readonly="readonly"
runat="server"> )

Thank you

2014-09-02 10:50 GMT+02:00 Neha Kadam notifications@github.com:

> Hello,
> 
> We have tested the plugin on IE 11. It is working fine.
> 
> From the snippet you included, it seems like you have initialized the
> plugin on the input element. But you are supposed to initialize it on the
> block level element you added specifically for DateTimePicker.
> 
> Please make sure that you have followed the steps listed while
> implementing -
> 
>    1.
> 
>    Include CSS and JS files
> 
> ```
> <link rel="stylesheet" type="text/css" href="DateTimePicker.css" />
> <script type="text/javascript" src="DateTimePicker.js"></script>
> 
> 2.
> ```
> 
>    In .html(or .aspx), add input element
> 
> ```
> <input type="text" data-field="date" readonly>
> 
> 3.
> ```
> 
>    In .html(or .aspx), add element as a base element for DateTimePicker
> 
> ```
> <div id="dtBox"></div>
> 
> 4.
> ```
> 
>    In script, initialize the plugin,
> 
> ```
> $(document).ready(function()
> {
>      $("#dtBox").DateTimePicker();
> });
> ```
> 
> Please refer to DateTimePicker Example
> https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicDatePicker.htm
> 
> Also check Demo http://curioussolutions.github.io/DateTimePicker/ on IE
> 11.
> 
> Thank You.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CuriousSolutions/DateTimePicker/issues/13#issuecomment-54124377
> .

## 

Alessandro Villani
MCSD Web Applications
