### ISSUE TITLE
bower is not updated to the new location

### ISSUE THREAD

**Issue by zevero** [nehakadam/DateTimePicker#130]
On bower update I get

    bower curioussolutions-datetimepicker#^0.1.37     ENORESTARGET No tag found that was able to satisfy ^0.1.37
    
    Additional error details:
    No versions found in https://github.com/CuriousSolutions/DateTimePicker.git

**Comment by nehakadam** [comment]
Hey, thanks for reporting. I missed that point. 
You can install DateTimePicker using command `bower install flat-datetimepicker`

**Comment by zevero** [comment]
Hurray. Thank you!
