### ISSUE TITLE
How to use this lib in angular2 ionic 2

### ISSUE THREAD

**Issue by jd0048** [nehakadam/DateTimePicker#134]
i am facing issue in ionic 2 how can i used in angular 2 ionic2?

**Comment by nehakadam** [comment]
Tried in ionic version : 3.3.0

Steps followed : 

1. Created a project using ionic blank template 

2. In assets folder, created "js" folder and added jquery-1.11.0.min.js and DateTimePicker.js files.

3. In assets folder, created "css" folder and added DateTimePicker.css file.

4. Added following code in "src/index.html" file ( Before main.js file ) -
```
    <script type="text/javascript" src="assets/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="assets/js/DateTimePicker.js"></script>

    <link href="assets/css/DateTimePicker.css" rel="stylesheet">
```
5. Added following code in "src/pages/home/home.html" file ( Inside ion-content ) - 
```
    <p>Date : </p>
    <input type="text" data-field="date" readonly>

    <div id="dtBox"></div>
```
6. In "src/pages/home/home.ts" file -

   Added following code after import statements
```
    declare var $:any;
```
  Added following code inside constructor function -
```
    $(document).ready(function()
    {
	$("#dtBox").DateTimePicker();
    });
```
