### ISSUE TITLE
Cant Get Timepicker

### ISSUE THREAD

**Issue by lenichols** [nehakadam/DateTimePicker#14]
My script works perfect for date-time mode but i need only to display time but it says function is undefined. I even changed the mode in the original DateTimePicker.js but nothing. How do I get only the time to display? Please advise.

**Comment by lenichols** [comment]
Looks like my version of DateTimePicker.js was old. I downloaded and overwrite my old one and now the "Time" picker displays correctly. Quick fix! Thanks for a great script.

**Comment by nehakadam** [comment]
Thank You :)
