### ISSUE TITLE
is there a way to pick seconds ? 

### ISSUE THREAD

**Issue by thonatos** [nehakadam/DateTimePicker#15]
is there a way to pick seconds ? 

the source has options like "yyyy-mm-dd HH:mm:ss" , but add datetimeFormat attr seems not work fine ,  can you help me ?

**Comment by nehakadam** [comment]
Hello,
1. Picking Seconds
   Currently, there is no provision for picking seconds, but this feature can be added.
2. For DateTimePicker with "yyyy-mm-dd HH:mm:ss" Format, see example, [DateTime Formats](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/Format-Both.htm)
   If you want to modify DateTime Format in the Title, see example [HumanDateFormatting](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-HumanDateFormatting.htm).

Thank You.

**Comment by thonatos** [comment]
thanks for reply,
You did a great job, I have tried a lot of plugins ,  the best one is yours . hah~ , thanks again !

I do like it , but for the reason that i have to pick seconds , i finally use another plugin to complete what i need , but i think someone else may need it in future, they will appreciate what you done , :+1: .
