### ISSUE TITLE
Is there any way to pick up only year and month?

### ISSUE THREAD

**Issue by xiongchen2012** [nehakadam/DateTimePicker#18]
Thank for your works.
Is there any way to pick up only year and month?

I found the following one is able to pick up only year and month by passing parameter named "accuracy"  .

Also see:
https://github.com/sustainablepace/mobipick

**Comment by nehakadam** [comment]
Hi,

Currently, our plugin does't have this functionality, but we will incorporate it into the plugin.

Thank You.

**Comment by ghost** [comment]
Hi xio you can make a counter script to achieve what you want :). Use
Google Inspect to find the class for the date and make a css script
{visibility : hidden!important} to that tag.  Reminder use only to the date
class since you want to achieve year and month.

**Comment by nehakadam** [comment]
Hi,

Your solution will just hide the Date Component in the DateTimePicker. But more code needs to be changed -
1. code to format Date to display in input fields - `_setOutput` function
2. code to read and parse Date - `_parseDate` function

Thank You.

**Comment by ghost** [comment]
Sorry for my incomplete information, I was done this before on the same
project I created a custom JS but Its been a long time , I lost that
project T_T . Ill try to find it if I can and post sample.
