### ISSUE TITLE
Incompatible with Chrome on Android

### ISSUE THREAD

**Issue by hueyy** [nehakadam/DateTimePicker#19]
I'm running Lollipop with Chrome 39.02171.59 and the picker instantly opens and closes, making it unsable. Demo GIF below:

![demo gif](http://i.imgur.com/FfKl0HS.gif)

**Comment by carlosleopoldo** [comment]
I have the same problem but in Chrome for OS X, when I focus the field with TAB

**Comment by nehakadam** [comment]
Hello,

Thanks for reporting issue.
1. DateTimePicker opens and closes
   The issue of closing DateTimePicker on Mobile devices is fixed, you can check [Demo](http://curioussolutions.github.io/DateTimePicker/)
2. Issue while focusing DateTimePicker with TAB 
   Support for TAB-based navigation is added. You can check [Demo](http://curioussolutions.github.io/DateTimePicker/) and [Keyboard Navigation](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/KeyboardNavigation.htm)

Thank You.
