### ISSUE TITLE
dateSeparator

### ISSUE THREAD

**Issue by robinsm** [nehakadam/DateTimePicker#21]
When amending the dateSeperator to anything but '-', the datetimepicker seems to fall over and not display correctly.

I would like the component to output dates in the format : dd/mm/yyyy HH:mm

Am I going about it the correct way?

**Comment by nehakadam** [comment]
Hi,

It works for '/' dateSeparator. Try code below

```
$("#dtBox").DateTimePicker({

      dateSeparator: "/",
      dateFormat: "dd/mm/yyyy",
      timeFormat: "hh:mm AA",
      dateTimeFormat: "dd/mm/yyyy hh:mm:ss AA"

});
```
