### ISSUE TITLE
Twitter bootstrap modal issue

### ISSUE THREAD

**Issue by LiquidMechanix** [nehakadam/DateTimePicker#23]
If you put the datetime picker in a Twitter bootstrap modal, select/set a date/time, then close the modal, you can't open the modal again.

I found removing "$(document).unbind("click");" on line 577 fixed the issue. But I have no clue what other issues that will cause.

**Comment by nehakadam** [comment]
Hi,

DateTimePicker Twitter Bootstrap Modal is working in example I tried.
Just check [DateTimePicker in Bootstrap Modal](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/Bootstrap%20Examples/BasicExample-BootstrapModal.htm)
