### ISSUE TITLE
Bug! 

### ISSUE THREAD

**Issue by ellhn** [nehakadam/DateTimePicker#25]
I've discovered a minus bug.  When clicking inside minutes (dtpicker-compValue) and then click minus or plus sign (no matter which of the four buttons), DateTimePicker window closes without ever press Set or Clear buttons...
Do you have any idea how to fix it?
Thank you

**Comment by nehakadam** [comment]
It is not actually a bug.
To enable keyboard navigation, DateTimePicker is closed on focusout of last textbox (.dtpicker-compValue).
So, you will find this happening for all last .dtpicker-compValue elements.
Any suggestions regarding improving this functionality are welcome.

Thank You.
