### ISSUE TITLE
Bug with JQM.

### ISSUE THREAD

**Issue by davidalfassi** [nehakadam/DateTimePicker#27]
Bug with JQM.
After opening the Date Picker once, I can't open any JQM popup.

JQ Files :
jq : JQuery/jquery-1.7.2.js
jqm : jquery.mobile-1.4.2.js

**Comment by nehakadam** [comment]
Hi,

Thanks for reporting a bug.
This was caused due to unbinding of click, keyup and keydown events in `_hidePicker()` funtion.
You can check [JQM Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/jQuery%20Mobile%20Project/BasicExampleMobile.htm)

**Comment by davidalfassi** [comment]
Thanks!
