### ISSUE TITLE
How to disable all previous date & time

### ISSUE THREAD

**Issue by Srinucnu** [nehakadam/DateTimePicker#28]
I want to disable previous date and time from current minute. please help me with this.

Thanks in advance

**Comment by nehakadam** [comment]
Hi,

If `currentTime = new Date()` then, convert it into the Date, Time or DateTime Format you have specified in the settings as `dateFormat`, `timeFormat` or `dateTimeFormat`  -

DateTimeFormat - 

"dd-MM-yyyy HH:mm:ss"
"dd-MM-yyyy hh:mm:ss AA"
"MM-dd-yyyy HH:mm:ss"
"MM-dd-yyyy hh:mm:ss AA"
"yyyy-MM-dd HH:mm:ss"
"yyyy-MM-dd hh:mm:ss AA"

DateFormat -

"dd-MM-yyyy"
"MM-dd-yyyy"
"yyyy-MM-dd"

TimeFormat - 

"hh:mm AA"
"HH:mm"

You can use a function like this to convert Date in the format -

```
function dateTimeConvertor(tempDate)
{
    var sDate = tempDate.getDate() + "-" + (tempDate.getMonth() + 1) + "-" + tempDate.getFullYear();
    sTime = tempDate.getHours() + ":" + tempDate.getMinutes() + ":" + tempDate.getSeconds();
    return sDate + " " + sTime;
}
```

Set formatted Date, Time or DateTime to parameter `minDate`, `minTime` or  `minDateTime`.

Check [Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/PeriodRange-Parameters.htm)
