### ISSUE TITLE
Make AMD and CommonJS friendly

### ISSUE THREAD

**Issue by adrianfalleiro** [nehakadam/DateTimePicker#29]
What do you think about wrapping the plugin in a UMD declaration to make it compatible with AMD and CommonJS environments. 

Something similar to this https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

Also, removing Grunt and its plugins from `dependencies` in the `package.json` file as they're already under the `devDependencies` field and adding `jquery` as a dependency.

Happy to submit a PR if you think it would be a good idea

**Comment by nehakadam** [comment]
Yes, you can submit PR for making DateTimePicker CommonJS compatibile and
modifying package.json.
