### ISSUE TITLE
Use with jQuery Mobile

### ISSUE THREAD

**Issue by ghost** [nehakadam/DateTimePicker#3]
Hello, 

I don't have an issue, but rather a question, and I couldn't find anywhere else to inquire with the developers. 

Has anyone tried/successfully used this plugin with jQuery Mobile?

I am looking for a datetime picker combo that will work well with jquerymobile.

Thanks

**Comment by nehakadam** [comment]
Hi,

Yes, DateTimePicker can be used with jQuery Mobile. You can find the implementation in the demo included in the Repository.

jQuery Mobile Demo: https://github.com/CuriousSolutions/DateTimePicker/tree/master/demo/jQuery%20Mobile%20Project

Thank You

**Comment by ghost** [comment]
Thank you. I got this to work after much trouble. If you have a jquery mobile Panel the datetimepicker does not show due to the panel overlay z-index surpassing the z-index of the datetimepicker overlay.

By adding the below code to my CSS i was able to resolve.
.dtpicker-mobile{
    z-index: 9999;
}

**Comment by ghost** [comment]
actually set it on .dtpicker-overlay instead so it works on dropdown mode also

**Comment by ghost** [comment]
I am having an issue on using it alongside jquery validate though, any ideas with that? 

Chrome throws : Uncaught TypeError: Cannot read property 'settings' of undefined   whenever I click a field with the datetimepicker

**Comment by nehakadam** [comment]
Hi

Thanks for highlighting the z-index related issue while using plugin with jQuery Mobile.

We are using a DateTimePicker along with jquery-validation (https://github.com/jzaefferer/jquery-validation).
We have used it to check whether Date Input Field is Empty. It is working fine. 

 It will be helpful in solving issue if you provide following details-
1. name or link of the jquery validate plugin you are using
2. Error Log (on which .js file you are getting Error "Chrome throws : Uncaught TypeError: Cannot read property  'settings' of undefined")
3. Code Snippet DateTimePicker and Validate Plugin Initialization

Thanks & Regards
Neha

**Comment by ghost** [comment]
jquery 1.11.0
jquery mobile 1.4.2 
jquery validation 1.12.0

Chrome console.: Uncaught TypeError: Cannot read property 'settings' of undefined jquery.validate.js:345

I am setting up the jquery validation and the dateBox in $(document).on('pagecreate', '#add-program', function(event, ui) { });   and not doc ready for reasons shown here: http://jqmtricks.wordpress.com/2014/03/26/jquery-mobile-page-events/ ... however I also tried it with doc ready just incase, and the same issue occurred

if I run validation without dateBox it works fine, if I run DateTimePicker without validation it works fine. when I run both the Chrome error throws when I click on a field that uses DateTimePicker, and the DateTimePicker does show, but then it will not work properly or close (due to the error).

I am looking myself for a solution also, I will let you know if I find a solution. I also would be interested in contributing to this project if you have any interest in working with me. I really like the DateTimePicker and would like to be sure it stays working well with jQuery Mobile for the forseeable future

**Comment by ghost** [comment]
also not I have tried moving around the order of the js files to see if it mattered and it did not help. I also tried setting up the datetimepicker before setting validation, and after. Also makes no difference

**Comment by ghost** [comment]
it does still do it even if I dont require that field that uses the DateTimePicker

**Comment by ghost** [comment]
Oh my, it was a typo issue. I've been looking at it for days too. Sigh. Sorry to waste your time

**Comment by nehakadam** [comment]
Hi

Sincere thanks for taking time to look into the plugin.
Of course we would be glad to work together with you. What more additions do you think we can incorporate.

Also just give us few more days & you will love our another creation CalenStyle-Modern Event Calendar.

Let us know about your ideas.

Thanks once again

Neha

**Comment by ghost** [comment]
can't wait to see it. 

Is there an option now to change the format that the date shows in the picker (I know there is for the text field, but I'm referring to the picker itself - above the plus signs)? That would be a nice feature. 

Also, an option to not use the set/clear buttons and just have the text field update as you hit the + or - would be nice. Instead of clicking the "X" to close the picker you could just focus off of it and it would close.

**Comment by ghost** [comment]
i cannot seem to change the maxDate fieldwithout editing the plugin directly

**Comment by ghost** [comment]
I have found what I believe is an event delegation issue with jQuery Mobile. With the way jQuery mobile handles "pages" there are often issues wih incorporating other plugins if you have forms in your app that use ajax submission.

For example:

If I have a datetimepicker on a page, then I leave that page and go to several other pages, then return to the page with the datetimepicker (where all the page transitions/form submissions are happening via ajax) then when I return the datetimepicker does not work.

After some debugging I have found that this is because dtPickerObj.dataObject.oInputElement  is not null, so the showDateTimePicker function is never called.  I am trying to find how this can be resolved as we speak

**Comment by ghost** [comment]
This also happens if I go from one page with a datetimepicker to another page with a different datetimepicker

**Comment by ghost** [comment]
I added dtPickerObj.dataObject.oInputElement=null; above the if condition in the _inputFieldFocus function and it seems to have fixed my issue. The datetimepickers are now working even if i navigate to all different kinds of pages. 

The only issue happening as a result is from time to time in the console I see Uncaught TypeError: Cannot read property 'top' of undefined DateTimePicker.js:302  (seems to only show when I navigate to a page without a datetimepicker), but this does not seem to break my app in any way. We should try to find a permanent solution for this though, as multiple event listeners may be still being added to the DOM

**Comment by nehakadam** [comment]
Hello,

1.Date/Time Picker Format in the Header Section
Currently, a descriptive Date/Time Format is used in the Header section. But it can be easily changes in the _setCurrentDate function. You can suggest Date/Time Formats, if any.

2.Visibility of Set/Clear Buttons and Close button in Header Section
I have added buttonsToDisplay setting variable, where you can specify Buttons you want to display on the DateTimePicker.

3.Change Values in Input Element on Every Increment or Decrement
I have added setValueInTextboxOnEveryClick settings variable, on setting it to true values in the Input Element will change on Every Increment or Decrement.

4.Close Dialog on Off Focus
Added this functionality 

5.maxDate
Check example https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/PeriodRange-Both.htm
Specify minDate and maxDate in the same Date/Time Format you have set (dateFormat, timeFormat, dateTimeFormat).

6.Issue on change page
I have added dtPickerObj.dataObject.oInputElement = null; in function _addEventHandlersForInput. Just check an example to illustrate it (https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/jQuery%20Mobile%20Project/BasicExampleMobileWithLink.htm). See whether it is working for your app and let me know. 

Thanks & Regards,
Neha

**Comment by ghost** [comment]
This features are great. Small request on the item 4 Close Dialog on Off Focus. Could you make it so that the DTP goes away if the user clicks tab on the keyboard or clicks somewhere else on the page outside of the DTP area? Like jQuery UI Datepicker does and most other datepickers do. Other than that, all of this is great news.

When do you anticipate the event calender? I have a great need for a good event calendar. Thanks!

**Comment by nehakadam** [comment]
Hello,

I have updated plugin based on your suggestions.
Can you please test it on mobile?

We are bit busy on other project so can not make proper time estimation of CalenStyle.

Thanks & Regards,
Neha

**Comment by ghost** [comment]
Now as soon at I click the field with the DTP, it shows and then immediately hides, without any interaction. It will not stay showing no matter what I do

**Comment by nehakadam** [comment]
Hello,

Thanks for testing plugin. I also tested it on mobile. It is not working properly. It was working well on browser.  So I have committed the older version again.
