### ISSUE TITLE
fill input field with date from database

### ISSUE THREAD

**Issue by francescodisciascio** [nehakadam/DateTimePicker#34]
Hi,
I'm using this plugin to create and edit an entity Event. It has a start and an end. They are both saved as Date into the mysql database.
In creation of Event everything works ok, I've also set up a custom separator and a date time format.
I also need that, when user want to change start or end date, it is shown into a same input field, but it is shown with another format, for example

2015-04-09 13:50:00.0

and when I click on the input field I have the following exception on console:

TypeError: sString1 is undefined
on line 1747 of DateTimePicker.js

Why does it happens?

**Comment by nehakadam** [comment]
Hi,

This error may be due to dateTimeFormat which not supported by DateTimePicker. If you specify dateSeparator, timeSeparator and dateTimeFormat you used, the problem will be more clear.
Please add DateTimePicker initialization code which in which you are getting an error.

**Comment by francescodisciascio** [comment]
this is the code for initialization:

$(document).ready(function() {
$("").DateTimePicker({
dateSeparator: "/",
dateFormat: "dd/mm/yyyy",
timeFormat: "hh:mm AA",
dateTimeFormat: "dd/mm/yyyy hh:mm:ss aa"
});
}

when I pick up date for a new event, everything works correctly, but when I use same form with existing event, it is filled with wrong format and nothing happens if I click on field...

**Comment by nehakadam** [comment]
This code is working.

"2015-04-09 13:50:00.0" format cannot be parsed and displayed in DateTimePicker .
If you are want to use dateTimeFormat "2015-04-09 13:50", you can use
 `dateTimeFormat: "yyyy-MM-dd hh:mm:ss"`.

You can also format datetime string in the header using `formatHumanDate()`.

**Comment by francescodisciascio** [comment]
That code works only if field starts empty, but if I would like to display a date taken from database to modify it, how can I use the datetime?
I'm using Grails and I'm trying to integrate the dateTimePicker into a field, so I use the same gsp page for creation and modifications of an entity...

**Comment by francescodisciascio** [comment]
Can you perform an example of formatHumanDate()?

**Comment by nehakadam** [comment]
1. Set datetime string in input field

It cannot work in this case. 
You will have to insert formatted date in the input field, then it will work.

For time being you can use this code set value in the database.

```
$("#dtBox").DateTimePicker({

    dateFormat: "MM-dd-yyyy",
    timeFormat: "HH:mm",
    dateTimeFormat: "MM-dd-yyyy HH:mm:ss AA",

    addEventHandlers: function()
    {
        var oDTP = this;

        oDTP.dataObject.oInputElement = $("#datetime"); // $("#datetime") Input field
        oDTP.settings.mode = "datetime";
        oDTP.dataObject.sDateTimeFormat = oDTP.settings.dateTimeFormat;
        oDTP.dataObject.bIs12Hour = true;
        $("#datetime").val(oDTP._setOutput());

        oDTP.dataObject.oInputElement = null;
        oDTP.settings.mode = "";
        oDTP.dataObject.sDateTimeFormat = "";
                oDTP.dataObject.bIs12Hour = false;
    }

});
```

I will add this feature in the plugin.
1. [formatHumanDate Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-HumanDateFormatting.htm)

**Comment by francescodisciascio** [comment]
I've added that code.
In creation it works correctly as before. If I fill field with data from db, it is formatted as described above and if I click on field, in console I read as follows:

TypeError: sString1 is undefined 
on row 1747 of DateTimePicker.js

**Comment by nehakadam** [comment]
See whether code in [Example - Set Input Fields](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-SetDateTimeOnLoad.htm) works for you.

You can also try `getDateTimeStringInFormat()` if `setDateTimeStringInInputField ()`, does not work.
