### ISSUE TITLE
[Feature request] formatHumanDateTime

### ISSUE THREAD

**Issue by re1d1** [nehakadam/DateTimePicker#35]
Hi,

first of all thank you for the nice work and DateTimePicker.

I have a feature request. It would be nice if you can define a seperate function for each type of Date, Time or DateTime for human readable Output, like it can be defined for "formatHumanDate".

Something like formatHumanDateTime.

yours sincerely

re1d1

**Comment by nehakadam** [comment]
Hi,

Thanks.

Your request can be implemented in two ways -
1. Write separate functions -`formatHumanDate`, `formatHumanTime`, `formatHumanDateTime`
2.  Write a single function formatHumanDateTime with DateTime Format String as a parameter, in which multiple formats can be specified in a single function.

```
formatHumanDateTime(sDateTimeFormat, oDateObject)
{
    if(sDateTimeFormat === "DD, MM dd, YYYY")
    {
        return oDateObject.dayShort + ", " + oDateObject.month + " " + oDateObject.dd + ", " + oDateObject.yyyy;
    }
}
```

I think second option will be better.

**Comment by re1d1** [comment]
i think both solutions are ok :+1:
