### ISSUE TITLE
What about internationalization?

### ISSUE THREAD

**Issue by monecchi** [nehakadam/DateTimePicker#4]
Hi there. Congrats for the great plugin!

Sorry for the numb question, but I'm new to web development and I've been trying to manually translate the plugin, so my doubt is: Is there a way to set other languages to it?

Thanks in advance.

**Comment by nehakadam** [comment]
Hello,

Thank you for feedback.

If you want to implement internationalization for only translating strings then you can do it just by replacing some settings parameters. If you want a different Date/Time format then plugin needs to be modified. Your suggestions for a new Date/Time Format are welcome.

List of Parameters for Translation -
1. shortDayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
2. fullDayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
3. shortMonthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
4. fullMonthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
5. titleContentDate: "Set Date"
6. titleContentTime: "Set Time"
7. titleContentDateTime: "Set Date & Time"
8. buttonsToDisplay: ["HeaderCloseButton", "SetButton", "ClearButton"]
9. setButtonContent: "Set"
10. clearButtonContent: "Clear"

Thanks & Regards,
Neha

**Comment by monecchi** [comment]
Hi there. Thanks for your reply. It help me a lot!!
