### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by victorfugiwara** [nehakadam/DateTimePicker#40]
Hi, thanks for the component. It's exactly what I was looking for.

I'm studying some technologies and I'm using angular. The component works fine, but its values isn't setted on the $scope variable of angular. 
The others inputs in the page are working fine with angular.

Have you any idea of what's happening?

**Comment by nehakadam** [comment]
Sorry Victor. I don't have much idea about working of AngularJS. 
I came across [Common Pitfalls](https://docs.angularjs.org/misc/faq#common-pitfalls). Read `DOM Manipulation` part of it.
The problem may be because input field value is modified using jQuery.
`ng-change` can be used to capture input field value changes and set value in `$scope` variable.

**Comment by victorfugiwara** [comment]
Thanks for the help.
The problem really is in angular.
Just to give an example: https://jsfiddle.net/dh6hmswa/
Actually, if the value of the field is changed via javascript, angular didn't get the changes.

Thanks for all.

**Comment by guaerguagua** [comment]
@victorfugiwara 
I am faceing the same problem.
How did you solve the problem?

**Comment by guaerguagua** [comment]
@nehakadam 
Thanks for the component.It is really beautiful.
I am trying use the ng-change but seems the function does not called.

**Comment by nehakadam** [comment]
Hi,

Thanks.

DOM Manipulations done using jQuery do not trigger change event.

Please read [how-to-trigger-ng-change-from-jquery](http://stackoverflow.com/questions/24330467/how-to-trigger-ng-change-from-jquery).

I tried the solution on the example given by Victor, example is working with it.
`angular.element(document.getElementById('test')).triggerHandler('change');`

Please see [Working Example](https://jsfiddle.net/techgeeek/0qr6qsjk/2/)

Hope you find it useful.

**Comment by nehakadam** [comment]
I have added [DateTimePicker with AngularJS](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/AngularJS/BasicDatePicker-AngularJS.htm) demo. Download DateTimePicker 0.1.23 and check whether this is what you want.

Though this is a working demo of DateTimePicker with AngularJS, please suggest modifications if it is invalid or inefficient workaround.

**Comment by nehakadam** [comment]
Added [AngularJS Exmaples].(https://github.com/CuriousSolutions/DateTimePicker/tree/master/demo/AngularJS)
