### ISSUE TITLE
dateSeparator - only dash and slash ??

### ISSUE THREAD

**Issue by paulrevival** [nehakadam/DateTimePicker#41]
Hello! I'm trying to configure this datepicker, but can it work with dot(".") as dateSeparator? And can I set "shortMonth" to returning date like "01 Dec 2014" ?? thanks!

**Comment by nehakadam** [comment]
Hi Paul,

DateTimePicker works with dot(".") or space(" ") as a Date Separator.

To set dot(".") as a `dateSeparator` - 

```
$("#dtBox").DateTimePicker(
{
    dateFormat: "dd.MMM.yyyy",
    dateSeparator: "."
});
```

To set space(" ") as a `dateSeparator` - 

```
$("#dtBox").DateTimePicker(
{
    dateFormat: "dd MMM yyyy",
    dateSeparator: " "
});
```

Thanks!

**Comment by byjrubira** [comment]
Hi! 
I'm trying to set the dateFormat like this...

`  $("#dtBox").DateTimePicker({
				dateFormat: "dd.MMM.yyyy",
				dateSeparator: "."
			});`

But, when i show up the pop up all the fields are show in blank.

Thank you in advance!
