### ISSUE TITLE
fill second field with first field value and validation

### ISSUE THREAD

**Issue by francescodisciascio** [nehakadam/DateTimePicker#42]
Hi, I have two input fields with date. They describes starting and ending time of an event.
I would like that, when user selects the first datetime, the second is automatically filled with the same value. I would also add a sort of validation that allows me to check if datetimes are correct (first datetime must be previous of second datetime)
Thanks

**Comment by nehakadam** [comment]
Hi,

DateTimePicker has functionality for validating StartDateTime and EndDateTime. 
See example - [StartEnd-DataAttributes Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/StartEnd-DataAttributes.htm)
Read - `data-startend` and `data-startendelem` in [Documentation](http://curioussolutions.github.io/DateTimePicker/).

You can set a date selected as Start Date in the End Date input field in `afterHide` callback function.

Thank You.
