### ISSUE TITLE
Problem with setting input values to datetimepicker manually

### ISSUE THREAD

**Issue by Ramu162** [nehakadam/DateTimePicker#43]
Hi,

Want to set time values manually in input box by typing, but it is not updating the manually typed values in the result box. Also when you delete the hour input box value and pressed "Tab" key to go in next input box for selecting the minutes values, it updating the hour input box values to "NaN" values.

**Comment by nehakadam** [comment]
Hi,
1. When you input values by typing, it will be reflected in DateTimePicker Header section on focus out event input field.
2. If you delete value and press TAB, all fields will show NaN. You will not be able to change the value. 

Thanks for reporting a bug.

**Comment by Ramu162** [comment]
Hi,
Thanks for quick reply.
How can we resolved these issues.

**Comment by nehakadam** [comment]
You can replace following lines of code in `_getValuesFromInputBoxes` method

```
dtPickerObj.dataObject.iCurrentHour = parseInt($(dtPickerObj.element).find(".hour .dtpicker-compValue").val());
dtPickerObj.dataObject.iCurrentMinutes = dtPickerObj._adjustMinutes(parseInt($(dtPickerObj.element).find(".minutes .dtpicker-compValue").val()));
```

with

```
dtPickerObj.dataObject.iCurrentHour = parseInt($(dtPickerObj.element).find(".hour .dtpicker-compValue").val()) || dtPickerObj.dataObject.iCurrentHour;
dtPickerObj.dataObject.iCurrentMinutes = dtPickerObj._adjustMinutes(parseInt($(dtPickerObj.element).find(".minutes .dtpicker-compValue").val())) || dtPickerObj.dataObject.iCurrentMinutes;
```

I will update repo later.

**Comment by Ramu162** [comment]
Hi Neha,
Thanks for the help.
NaN issue is resolved, but we are facing issues with maually typed values in input field specially for 12 PM. Also have restricted the minTime : local time and maxTime: 11:59 PM. This issues are not coming when we are changing values through Up - Down arrows.

**Comment by nehakadam** [comment]
Hi,
You can download updated version of DateTimePicker and check whether your issue is solved.

**Comment by Ramu162** [comment]
Hi Neha,
Have updated the css and js from your repo, but still facing the same 12 PM issue. Please find the attached file for more details about the time picker.
![timepicker-issue](https://cloud.githubusercontent.com/assets/10653360/8104668/2510c3ec-1050-11e5-8d5a-beb695d9bd9c.gif)

**Comment by nehakadam** [comment]
Please check feature you want in some example in DateTimePicker Demo folder (e.g. Format-parameters.htm). As far as I checked in this example, I could type in 12:00 AM and 12:00 PM value.
