### ISSUE TITLE
Facing problem when using two date picker in same page

### ISSUE THREAD

**Issue by atulintel** [nehakadam/DateTimePicker#45]
I am facing one issue, i have taken the two date picker and i have set the max-date and min-date for both, but the problem is, it is only considering min-date and max-date of only one, not for the other date picker, what to do ?

**Comment by nehakadam** [comment]
Please refer to examples - [Date Range](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/PeriodRange-DataAttributes.htm). In this example, you can add one more date field and check. It is working fine.

Or try code below -

HTML code -

```
<p>Date 1 : </p>
<input type="text" data-field="date" data-min="01-03-2012" data-max="01-03-2016" readonly>

<p>Date 2 : </p>
<input type="text" data-field="date" data-min="01-03-2015" data-max="01-03-2016" readonly>

<div id="dtBox"></div>
```

Javascript Code -

```
$("#dtBox").DateTimePicker();
```

**Comment by atulintel** [comment]
Thanks for answer, it solved the problem
