### ISSUE TITLE
Multiple Pickers with Different Minute Intervals

### ISSUE THREAD

**Issue by randdusing** [nehakadam/DateTimePicker#48]
Is it possible to have multiple pickers? For example, how could I have two time pickers, one with a 1 minute interval, and another with a 5 minute interval? It doesn't seem like I can assign an input to a specific picker.

**Comment by nehakadam** [comment]
You can achieve this by adding 2 more DOM elements. Try following code

**HTML**

```
<div class="minutes-1">
    <p>Time : (1 minute)</p>
    <input id="input-1" type="text" data-field="time" readonly>
</div>

<div class="minutes-5">
    <p>Time : (5 minutes)</p>
    <input  id="input-2" type="text" data-field="time" readonly>
</div>

<div id="dtBox-1"></div>

<div id="dtBox-2"></div>
```

**Javascript**

```
$(document).ready(function()
{
    $("#dtBox-1").DateTimePicker(
    {
        parentElement: ".minutes-1",
        minuteInterval: 1
    });

    $("#dtBox-2").DateTimePicker(
    {
        parentElement: ".minutes-5",
        minuteInterval: 5
    });             
});
```

**Comment by randdusing** [comment]
Thank you, everything works well now!

**Comment by nehakadam** [comment]
Added [Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-MinuteInterval-Multiple.htm).
