### ISSUE TITLE
Undefined Value

### ISSUE THREAD

**Issue by JordanSayner** [nehakadam/DateTimePicker#49]
Hi,

Im trying to use this as a datapicker for selecting a departure date. but when i try and send the data with an ajax call the value is showing up as undefined. 

I have created a test area with jsfiddle and im also getting undefined on there. What am i doing wrong? / Is this a bug within the plugin?

My jsFiddle is http://jsfiddle.net/Lpkerxv8/ 

Here is my test code.

``` html
<input runat="server" id="tbStartDate" CssClass="tbDate tbStartDate" type="text" data-field="date" placeholder="Departure Date" readonly>

<div id="dtBox"></div>
<br /> 
<br />   
<a class="btn-filter-properties">
    Search
</a>
```

``` javascript
$("#dtBox").DateTimePicker({
    titleContentDate: "",
    dateFormat: "dd/mm/yyyy",
    dateSeparator: "/",
});

$(".btn-filter-properties").click(function () {
    alert("Departure Date: " + $(".tbStartDate").val());
});
```

**Comment by nehakadam** [comment]
Hi Jordan,

Change 

`alert("Departure Date: " + $(".tbStartDate").val());`

To

`alert("Departure Date: " + $("#tbStartDate").val());`

**Comment by JordanSayner** [comment]
I see where i went wrong, i change the input from a asp:TextBox to a standard input but forgot to change the CssClass to class. doh!! I feel a bit silly now. feel free to delete my stupidity, you can tell i have that Monday feeling

**Comment by nehakadam** [comment]
It's Ok, but Issue cannot be deleted.
