### ISSUE TITLE
Multiple TimePicker not working properly

### ISSUE THREAD

**Issue by AmitJadli1987** [nehakadam/DateTimePicker#51]
Hi Guyz,

I am using this plugin for one of my website and on multiple text fields, But the problem is when one datetimepicker is open and i click on the another time picker text box there is no intreaction happens,, so i just want to destroy the another popup's and reinitialize the datetimepciker to the clicked textbox....

Please Help Me on this...

**Comment by nehakadam** [comment]
Hi Amit,

Replace "_inputFieldFocus" function, in your DateTimePicker.js

```
_inputFieldFocus: function(e)
{
    var dtPickerObj = e.data.obj;
    if(dtPickerObj.dataObject.oInputElement == null)
    {
        dtPickerObj.showDateTimePicker(e.target);
    }
    else
    {
        dtPickerObj._hidePicker(0);
        dtPickerObj.showDateTimePicker(e.target);
    }
    dtPickerObj.dataObject.bMouseDown = false;
},
```

This will work for the behaviour you are expecting with `isPopup: false`.
You can check this in "View-BasedOnDocumentWidth.htm" example in Demo folder of plugin distribution file.
