### ISSUE TITLE
Dialog blink twice

### ISSUE THREAD

**Issue by creolyte** [nehakadam/DateTimePicker#52]
When I implement the datetimepicker using [input data-field="date"] tag, when click it blink twice. It happen on the demo site too.

But if I implement on [span data-field="date"] tag, it works.
The issue is I want to implement using [input] so it will POST by [form] but it will cause double blinking effect. Not sure is just me or anyone having this issue as well?

Is there any workaround? Thanks.

**Comment by nehakadam** [comment]
Hey thanks for Reporting issue.
It was happening on [DateTimePicker Website](http://curioussolutions.github.io/DateTimePicker/).

If you are looking for a quick fix, just replace line 318 in `_inputFieldClick` function,

 `if($(this).prop("tagName") !== 'input')` 

with

`if(!dtPickerObj._compare($(this).prop("tagName"), "input"))`.

**Comment by creolyte** [comment]
Awesome ! Tested and it is working. Thanks !
