### ISSUE TITLE
"Current date" within popup is stale

### ISSUE THREAD

**Issue by burnstek** [nehakadam/DateTimePicker#54]
Say you call $("#el").DateTimePicker() at 1pm... and you sit on the page for 2 minutes.  By the time you focus on the field, thus opening the popup, the popup will still indicate that it's 1pm and not 1:02pm.

Seems like it would be better to recalculate the current time every time the popup is opened?

**Comment by nehakadam** [comment]
Hi,

You can achieve this by using following code - 

HTML -

```
<p>DateTime : </p>
<input type="text" data-field="datetime" readonly>

<div id="dtBox"></div>
```

Javascript -

```
$(document).ready(function()
{
    $("#dtBox").DateTimePicker(
    {
        beforeShow: function(oInputElement)
        {
            var oDTP = this;

            if($(oInputElement).val() === "")
                oDTP.settings.defaultDate = new Date();
        }
    });
});
```

See [Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/Callback-beforeShow.htm).

**Comment by burnstek** [comment]
Thank you so much; great idea.
