### ISSUE TITLE
custom firing picker show 

### ISSUE THREAD

**Issue by iVovolk** [nehakadam/DateTimePicker#56]
Hi! Is there any way to custom trigger picker show event? In my case i need ability to show picker by clicking on other element.
And i having a trouble with iOs 8.2 safari on iphone 4s. It ignores readonly prop in markup and firing default focus event.
Thanks!

**Comment by nehakadam** [comment]
Try the code in [Custom Event Example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-CustomEvent.htm)

**Comment by iVovolk** [comment]
Thats perfect! Thanks.
