### ISSUE TITLE
For the time... how to get 24hr format?

### ISSUE THREAD

**Issue by lenichols** [nehakadam/DateTimePicker#6]
12:00pm,1:00pm,2:00pm,3:00pm... instead of 12:00pm,13:00pm,14:00pm and so on?

**Comment by nehakadam** [comment]
Hello,

You can set Time Format in plugin settings or data attributes.

Time Format 
1.  Plugin settings Parameter - 
     timeFormat: "HH:mm AA"
2. HTML5 Data Attribute - 
     data-format="hh:mm AA"

Time Format Options - 
1. "HH:mm" (default)
2. "hh:mm AA"

DateTime Format 
1.  Plugin settings Parameter - 
     dateTimeFormat: "dd-MM-yyyy hh:mm:ss AA"
2. HTML5 Data Attribute - 
     data-format="dd-MM-yyyy hh:mm:ss AA"

DateTime Format Options - 
1. "dd-MM-yyyy HH:mm:ss"
2. "dd-MM-yyyy hh:mm:ss AA"
3. "MM-dd-yyyy HH:mm:ss"
4. "MM-dd-yyyy hh:mm:ss AA"
5. "yyyy-MM-dd HH:mm:ss"
6. "yyyy-MM-dd hh:mm:ss AA"

Check Demo Example - 
https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/Format-Both.htm

Thanks & Regards,
Neha
