### ISSUE TITLE
not support zepto

### ISSUE THREAD

**Issue by hanai** [nehakadam/DateTimePicker#61]
is there any way to make it support zepto?

**Comment by nehakadam** [comment]
Try this code. I have not checked it fully, but you can try this. [Example](https://github.com/CuriousSolutions/DateTimePicker/tree/master/demo/Basic-Zepto.htm)

Some events(e.g. blur) are not firing and and selector(e.g. tabindex=[]) are not working in Zepto. So, it may break sometimes like on switching tab and while navigating between input elements using TAB key.

You will have to use a [custom build](https://github.com/CuriousSolutions/DateTimePicker/tree/master/demo/zepto-1.1.6-Custom.min.js) of Zepto with Base Modules plus "fx", "fx_methods", and "data" modules.
