### ISSUE TITLE
If a datetime format has been defined, but initial data without time portion, runtime error will be given out

### ISSUE THREAD

**Issue by athensy** [nehakadam/DateTimePicker#62]
At line #1832 of DateTimePicker.js, if datetime format has been defined, it assumes the time portion will always exist. However, this assumption is not always true. The following example is demonstrated how to break it:

input type="text" value="2015-09-12" data-field="datetime" data-format="yyyy-MM-dd HH:mm:ss" readonly

I suggest to modify it as follows:

sTime = sArrDateTime[1];
if (typeof sTime == 'undefined') {
  if(oDTP.oData.bIs12Hour) {
     sTime = "12:00:00 AM";
  }
  else {
    sTime = "00:00:00";
  }
}

**Comment by nehakadam** [comment]
:+1:
