### ISSUE TITLE
Missing Cases in _parseDateTime()

### ISSUE THREAD

**Issue by D40298008** [nehakadam/DateTimePicker#67]
Hello,

If you have the dateTimeFormat set to "MM-dd-yyyy hh:mm AA", it is not popping up the date-time picker with the pre-populated date (only the time).  The date gets filled in with the default.

I think you are missing some cases when parsing the date portion in your if-else block within the _parseDateTime() function.  For example <code>bArrMatchFormat[11]</code> would (I think) cover this one but there are others missing too.

**Comment by nehakadam** [comment]
Thanks for reporting. Conditions for DateTimeFormats without seconds component were missing.
