### ISSUE TITLE
AM/PM button not working

### ISSUE THREAD

**Issue by simonlisen** [nehakadam/DateTimePicker#68]
Hi,

I use DateTimePicker on my project today and find AM/PM compButton dose not work. Other compButton work well. After debugging I fixed it by the following change:

DateTimePicker.js, Line 1589:

$(oDTP.element).find(".meridiem .dtpicker-compButton *").click(function(e)
->
$(oDTP.element).find(".meridiem .dtpicker-compButton").click(function(e)
Remove the asterisk.

Please verify this problem. Hope my solution helps.

Thanks,

Sen

**Comment by nehakadam** [comment]
Thanks for reporting. Your solution is correct. But if you you want to customize beuttons then you will have to use

```
$(oDTP.element).find(".meridiem .dtpicker-compButton, .meridiem .dtpicker-compButton *").click(function(e) 
{
});
```
