### ISSUE TITLE
Change popup target...

### ISSUE THREAD

**Issue by lenichols** [nehakadam/DateTimePicker#7]
Can you please tell me how to make the popup open above the parent window? i have a single page app im using this on but it pops up in the child partial-view rather than above the parent item. Any help with this would be appreciate!

**Comment by nehakadam** [comment]
Hello,

DateTimePicker pops up inside the view in which it is added. So, if you want it to be popped above your parent view you will need to add it in the parent view. 
For example,
if you consider https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicDateTimePicker.htm then you will need to add 

<div id="dtBox"></div>

inside your parent view. 

z-index of overlay (.dtpicker-overlay) is 2000, so if z-index of your parent view is greater than 2000 then you will need to change z-index of .dtpicker-overlay inside DateTimePicker.css file to a value greater than your parent view.

Thanks & Regards,
Neha
