### ISSUE TITLE
AM/PM with datetime picker

### ISSUE THREAD

**Issue by bwobst** [nehakadam/DateTimePicker#71]
Hi,

I'm not able to get AM/PM working with the datetime picker. I've set timeFormat: "hh:mm AA", but only get the 24-hour clock.

If I try to set dateTimeFormat: "dd-MM-yyyy hh:mm AA", the date/time selector area goes blank.

Any ideas?

Thanks,
Brian

**Comment by nehakadam** [comment]
Hi,

There was a problem with increment/decrement buttons used to change AM/PM , see #68. It is fixed now, you can download and use latest version of DateTimePicker.
