### ISSUE TITLE
How to set default input-field value?

### ISSUE THREAD

**Issue by francisfeng** [nehakadam/DateTimePicker#72]
![image](https://cloud.githubusercontent.com/assets/1040288/11451318/d0acc804-95fc-11e5-99f0-dae43652fbe7.png)

I want values show in the input fields right after the page is rendered, just like the latter one showed in the above screenshot.

But the fact is that I have to select a date to achieve that. Before that, it's just empty input fields like the top one showed in the screenshot.  And the `init` callback function did't seem to work. It wouldn't take any parameters.

I've tired to give the input element a default value. But that wouldn't work. And the docs on http://curioussolutions.github.io/DateTimePicker/ seems kindda obsolete.

Are there any solutions?

**Comment by nehakadam** [comment]
Yes, you can achieve this using `setDateTimeStringInInputField` function. It is listed in Function List of  [Documentation](http://curioussolutions.github.io/DateTimePicker/).

HTML Code

```
<p>Date : </p>
<input type="text" data-field="date" readonly>

<div id="dtBox"></div>
```

Javascript Code

```
$(document).ready(function()
{
    $("#dtBox").DateTimePicker(
    {
        init: function()
        {
        var oDTP = this;
        oDTP.setDateTimeStringInInputField();
    }
    });
});
```

**Comment by nehakadam** [comment]
@francisfeng 

DateTimePicker might not be working if you have downloaded it after Thursday. It is breaking. I am modifying script but if you are in hurry add following code to line number `1654` -

`if(oDTP.settings.settingValueOfElement)`

**Comment by nehakadam** [comment]
You can find Demo of setting values in input field [here](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/SetValueInInput.htm).

**Comment by francisfeng** [comment]
I have found out a workaround by giving `input` element a default value. 
Something like this: `<input type="text" value="2015-11-28" />`

And after checking out my code, I found out that I have comment line `1654` and I don't even know when I did that.

Anyway, it works now. Thanks.

**Comment by gt-leibin** [comment]
@francisfeng 

HTML codes

```
<input class="startDateTime1" type="text" data-field="datetime" data-startend="start" data-startendelem=".endDateTime1" readonly="" data-format="yyyy-MM-dd HH:mm:ss">
<input class="endDateTime1" type="text" data-field="datetime" data-startend="end" data-startendelem=".startDateTime1" data-format="yyyy-MM-dd HH:mm:ss" readonly="">
<div id="dtBox"></div>
```

JS codes

```
$("#dtBox").DateTimePicker({
        init:function(DateTimeObj){                 
            this.setDateTimeStringInInputField();           
        }
})
```

you can also deal with it like this

```
$("#dtBox").DateTimePicker({
     init:function(DateTimeObj){                    
        this.setDateTimeStringInInputField($(".startDateTime1"),new Date());            
        this.setDateTimeStringInInputField($(".endDateTime1"),new Date());          
    } 
})
```
