### ISSUE TITLE
Default date by timezone provided?

### ISSUE THREAD

**Issue by srdjanpejic** [nehakadam/DateTimePicker#73]
Is it possible to set defaultDate by timezone provided?

**Comment by nehakadam** [comment]
DateTimePicker does not have method to set DateTime in a Timezone. So you will have to supply DateTime converted in Timezone you want to display.

**Comment by nehakadam** [comment]
If you are using moment.js for timezone conversion you can use following code - 

```
var dThisMoment = moment().utcOffset("-08:00"),
 dThisJS = new Date(dThisMoment.year(), dThisMoment.month(), dThisMoment.date(), dThisMoment.hours(), dThisMoment.minutes(), dThisMoment.seconds(), 0);

$("#dtBox").DateTimePicker(
{
    defaultDate: dThisJS
})

```

**Comment by srdjanpejic** [comment]
I have to prepare datetime by timezone in backend and serve it to frontend where I'll use DateTimePicker.

I made some progress with beforeShow method, but I'm not sure if it's the right way.

**Comment by nehakadam** [comment]
You can set DateTime inside `init`, `addEventHandlers` or `beforeShow` callback function. To set date you can use `setDateTimeStringInInputField(inputElement, date)` function. See example, [BasicExamples-SetDateTimeOnLoad.htm](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-SetDateTimeOnLoad.htm)
