### ISSUE TITLE
Two dates and set minimum date

### ISSUE THREAD

**Issue by bralemili** [nehakadam/DateTimePicker#79]
From the API I cannot understand how to setup a minimum date (today's date).
I would like to have two date pickers, a 'start' and 'end' date range. 
When I enter a date for 'start', the minimum value of the 'end' should be the value entered for 'start'. (The 'end' date cannot begin before 'start', and 'start' cannot begin before today).
Thank you for any info!

**Comment by nehakadam** [comment]
`minDate`, `maxDate`, `minTime`, `maxTime`, `minDateTime` and `maxDateTime`, listed in [API Documentation](http://curioussolutions.github.io/DateTimePicker/) can be used to achieve this. 
You can also find [example](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/StartEnd-DataAttributes.htm) in the Demo folder of Repository.
