### ISSUE TITLE
BasicExamples-CustomEvent

### ISSUE THREAD

**Issue by Ariakas** [nehakadam/DateTimePicker#8]
When I click the "Show" button, a picker pops up but then immidiatly closes.
How to fix it?

**Comment by nehakadam** [comment]
Hello,

Thanks for feedback.
You will need to add `e.stopPropagation();` in your button Click Handler.
I have updated the code in [BasicExamples-CustomEvent](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/BasicExamples-CustomEvent.htm).

Thanks & Regards,
Neha

**Comment by Ariakas** [comment]
Thanks. It works. =)
