### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by travisfont** [nehakadam/DateTimePicker#80]
After inserting the provided example code I received the following error in my browser console:

> Uncaught TypeError: Cannot read property 'DateTimePicker' of undefined

Coming from line **11** on **DateTimePicker.js.**

I have all the require JavaScript files including the style CSS in my header (not shown in the below code). Note; all the JavaScript files are loading too.

What would even cause this to happen? Seems like some pattern calling is incorrect?

Note; using Chrome 47.

``` javascript
<script type='text/javascript' src='jquery-1.11.0.min.js'></script>
<script type='text/javascript' src='jquery-ui.min.js'></script>
<script type='text/javascript' src='jquery-ui.min.js'></script>
<script type='text/javascript' src='bootstrap.min.js'></script>
<script type='text/javascript' src='DateTimePicker.js'></script>
<script type="text/javascript">
jQuery(document).ready(function($)
{
    // query testing (NOTE: no error is thrown)
    if(typeof jQuery == 'undefined')
    {
        throw new Error('ERROR: Script requires jQuery');
    }

    $('#dtBox').DateTimePicker();

    $('#datefield').on('click',function(){
        alert('okay');
    });
});
</script>
```

**Comment by nehakadam** [comment]
Your code is working in Chrome 47. There may be some another issue.
