### ISSUE TITLE
Doubletap-zooming on mobile device

### ISSUE THREAD

**Issue by Mike8000** [nehakadam/DateTimePicker#85]
Hi Nehakadam

Thanks for the plugin. It's sleek and beautiful.

My only problem is the zooming effect when it's used on mobile devices.
Because users tend to tap fast to scroll on +/-, these actions become doubletap and resulting in annoying zooming effect.

I tried on a few scripts, such as: 
http://stackoverflow.com/questions/15804296/how-to-prevent-doubletap-zoom-in-ios-and-android
http://stackoverflow.com/questions/3103842/safari-ipad-prevent-zoom-on-double-tap

But all failed! I still like the plugin though. Hopefully some workaround solutions will stop it from zooming on mobile device. Thanks

**Comment by Mike8000** [comment]
I found the solution! after 2 days of testing on all available scripts.

**Comment by nehakadam** [comment]
Hi Mike,
Please share your solution, so that others might be benefited if they face similar issues.

**Comment by Mike8000** [comment]
I used this script:

```
// To prevent double tap zooming
(function($) 
{
  $.fn.nodoubletapzoom = function()
  {
    $(this).bind('touchstart', function preventZoom(e)
    {
      var t2 = e.timeStamp;
      var t1 = $(this).data('lastTouch') || t2;
      var dt = t2 - t1;
      var fingers = e.originalEvent.touches.length;
      $(this).data('lastTouch', t2);
      if (!dt || dt > 500 || fingers > 1)
      {
        return; // not double-tap
      }
      e.preventDefault(); // double tap - prevent the zoom
      // also synthesize click events we just swallowed up
      $(e.target).trigger('click');
    });
  };
})(jQuery);
$("body").nodoubletapzoom();
```

Source: https://stackoverflow.com/questions/3103842/safari-ipad-prevent-zoom-on-double-tap/21301712#21301712
Author: Inventillect

It will stop the whole page from zooming. But it works well for me.

**Comment by nehakadam** [comment]
Thanks Mike!!
Modified your comment to format code.
