### ISSUE TITLE
how to set something as simple as minDate

### ISSUE THREAD

**Issue by AakashGfude** [nehakadam/DateTimePicker#88]
I have tried :

$('#dtBox').DateTimePicker({
       minDate:0,
});
$('#dtBox').DateTimePicker({
       minDate:new Date(),
});

It says sDate.split is not a function .  so i tries giving the date by changing to string explicietly , but didnt work

**Comment by nehakadam** [comment]
See Examples - [Set Today as a min Date](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/PeriodRange-MinToday.htm) and [Set Min and Max Dates](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/PeriodRange-Both.htm).

**Comment by AakashGfude** [comment]
Thanks, works for me .
