### ISSUE TITLE
please allow "tab" in selecting between input fields

### ISSUE THREAD

**Issue by wlekin** [nehakadam/DateTimePicker#92]
Input fields only allow numbers, but I want to "tab" between input fields.

**Comment by nehakadam** [comment]
@wlekin Can you please explain what exactly you want?

**Comment by wlekin** [comment]
I want tab between input fields when I entering a date and time. 
When I tab between input fields, I suppose it will select and highlighting the next input field, but it place the cursor at end of text.

**Comment by nehakadam** [comment]
View Example [KeyboardNavigation.htm](https://github.com/CuriousSolutions/DateTimePicker/blob/master/demo/KeyboardNavigation.htm) on browser, I think this is what you want to implement.

**Comment by wlekin** [comment]
I do not get it. 
I want tab between input fields, which inside the "#dtBox" picker.
Beside tab, I cannot use arrow key to move the cursor, or ctrl + a to select all.
What I can do to select them is double click by mouse.

**Comment by nehakadam** [comment]
If you want text inside textfield to be highlighted while tabbing between textfields of DateTimePicker UI, similar to this [issue](http://stackoverflow.com/questions/10402067/selecting-textarea-text-when-tabbing), following will be the solution -

1.Add following code at the end of function definition `$('.dtpicker-compValue').focus(function()`,
    `$(this).select();`
1. Add following code at the end of function definition `$(".dtpicker-compValue").keyup(function(e)`,

```
    if(parseInt(e.keyCode ? e.keyCode : e.which) === 9)
        $(this).select();
```

Please let me know whether it is the proper solution so I can update code in repo accordingly.

**Comment by wlekin** [comment]
finally I did something like that:

```
$( '#dtBox' ).DateTimePicker( {
    afterShow : function () {
        $( '.dtpicker-compValue' ).keyup( function( e ) {
            if( parseInt( e.keyCode ? e.keyCode : e.which ) === 9|| parseInt( e.keyCode ? e.keyCode : e.which ) === 16|| parseInt( e.keyCode ? e.keyCode : e.which ) === 17 ) {
                $(this).select();
            }
        });
    },
});
```

**Comment by nehakadam** [comment]
This will also work.
