### ISSUE TITLE
Potential AM/PM issue?

### ISSUE THREAD

**Issue by madracer2469** [nehakadam/DateTimePicker#95]
Good day, 

I'm trying to use the CuriousSolutions DateTimePicker, but I'm running into an error when I try to insert the datetime into a MySQL database.

Shouldn't the AM/PM picker go from 11:59 PM to 12:00 AM? 
Currently (for me), it goes from 11:59 AM - 00:00 AM which seems to be causing an issue when I insert the time into a MySQL database. 

Here's my implementation:
(HTML - minimized)
<input class="medium" name="birthdate" required="required" data-field="datetime" style="text-align:center;" readonly/>  
(JS)
   $(function() {  
                     $(".dtBox").DateTimePicker({
                   dateTimeFormat:"MM-dd-yyyy hh:mm AA", 
                    maxDateTime: "06-31-2016 23:59"
                });

I apologize if this is caused by an oversight on my behalf and I would greatly appreciate your time and feedback. Thank you,
-Mike

**Comment by nehakadam** [comment]
@madracer2469 Thank for reporting error.

**Comment by madracer2469** [comment]
Thanks for your fast response! It seems to work in my updated JS. : D
Have a great day!
